const ShopActionType = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTION_FAILURE',
};
export default ShopActionType;
